package com.nex3z.examples.spring.data.mybatis.generator.model;

import java.io.Serializable;
import java.util.Date;
import org.joda.money.Money;

public class Book implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BOOK.ID
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BOOK.TITLE
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BOOK.PRICE
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    private Money price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BOOK.CREATE_TIME
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BOOK.UPDATE_TIME
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_BOOK
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BOOK.ID
     *
     * @return the value of T_BOOK.ID
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BOOK
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    public Book withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BOOK.ID
     *
     * @param id the value for T_BOOK.ID
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BOOK.TITLE
     *
     * @return the value of T_BOOK.TITLE
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BOOK
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    public Book withTitle(String title) {
        this.setTitle(title);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BOOK.TITLE
     *
     * @param title the value for T_BOOK.TITLE
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BOOK.PRICE
     *
     * @return the value of T_BOOK.PRICE
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    public Money getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BOOK
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    public Book withPrice(Money price) {
        this.setPrice(price);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BOOK.PRICE
     *
     * @param price the value for T_BOOK.PRICE
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    public void setPrice(Money price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BOOK.CREATE_TIME
     *
     * @return the value of T_BOOK.CREATE_TIME
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BOOK
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    public Book withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BOOK.CREATE_TIME
     *
     * @param createTime the value for T_BOOK.CREATE_TIME
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BOOK.UPDATE_TIME
     *
     * @return the value of T_BOOK.UPDATE_TIME
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BOOK
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    public Book withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BOOK.UPDATE_TIME
     *
     * @param updateTime the value for T_BOOK.UPDATE_TIME
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BOOK
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", price=").append(price);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}