package com.nex3z.examples.spring.data.mybatis.generator.mapper;

import com.nex3z.examples.spring.data.mybatis.generator.model.Book;
import com.nex3z.examples.spring.data.mybatis.generator.model.BookExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BOOK
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    long countByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BOOK
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    int deleteByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BOOK
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    @Delete({
        "delete from T_BOOK",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BOOK
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    @Insert({
        "insert into T_BOOK (TITLE, PRICE, ",
        "CREATE_TIME, UPDATE_TIME)",
        "values (#{title,jdbcType=VARCHAR}, #{price,jdbcType=BIGINT,typeHandler=com.nex3z.examples.spring.data.mybatis.generator.handler.MoneyTypeHandler}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="CALL IDENTITY()", keyProperty="id", before=false, resultType=Long.class)
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BOOK
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    int insertSelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BOOK
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    List<Book> selectByExampleWithRowbounds(BookExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BOOK
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    List<Book> selectByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BOOK
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    @Select({
        "select",
        "ID, TITLE, PRICE, CREATE_TIME, UPDATE_TIME",
        "from T_BOOK",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.nex3z.examples.spring.data.mybatis.generator.mapper.BookMapper.BaseResultMap")
    Book selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BOOK
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") Book record, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BOOK
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    int updateByExample(@Param("record") Book record, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BOOK
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    int updateByPrimaryKeySelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BOOK
     *
     * @mbg.generated Thu Mar 07 21:30:55 CST 2019
     */
    @Update({
        "update T_BOOK",
        "set TITLE = #{title,jdbcType=VARCHAR},",
          "PRICE = #{price,jdbcType=BIGINT,typeHandler=com.nex3z.examples.spring.data.mybatis.generator.handler.MoneyTypeHandler},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "UPDATE_TIME = #{updateTime,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Book record);
}